apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations: {}
  labels:
    name: oauth2-proxy
  name: oauth2-proxy
  namespace: kubeprod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      name: oauth2-proxy
