apiVersion: v1
data:
  authz_domain: aG9zdGVhY2hpbmcub3Zo
  client_id: Ymtwcg==
  client_secret: NmU5ZDRhNDMtMDc5OS00ZTE1LWI5NmQtYWRkN2I4NDJiZDRl
  cookie_secret: RHF5MGRCblUzUCtVRTdDVVhxTk5iTHkxNTJhaXNLd3Q=
kind: Secret
metadata:
  annotations: {}
  labels:
    name: oauth2-proxy
  name: oauth2-proxy-1f85277
  namespace: kubeprod
type: Opaque
