apiVersion: v1
data:
  config.yml: |
    global:
      resolve_timeout: 5m
    inhibit_rules:
    - equal:
      - alertname
      - cluster
      - service
      source_match:
        severity: critical
      target_match:
        severity: warning
    receivers:
    - name: email
    route:
      group_by:
      - alertname
      - cluster
      - service
      group_interval: 5m
      group_wait: 30s
      receiver: email
      repeat_interval: 7d
      routes: []
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    name: alertmanager
  name: alertmanager
  namespace: kubeprod
