apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: alertmanager
  name: alertmanager
  namespace: kubeprod
spec:
  ports:
  - name: alertmanager
    port: 9093
    targetPort: 9093
  selector:
    name: alertmanager
  type: ClusterIP
