apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9104"
    prometheus.io/scrape: "true"
  labels:
    name: mariadb-galera
  name: mariadb-galera
  namespace: kubeprod
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
  - name: metrics
    port: 9104
    protocol: TCP
  selector:
    name: mariadb-galera
  type: ClusterIP
