apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: mariadb-galera-headless
  name: mariadb-galera-headless
  namespace: kubeprod
spec:
  clusterIP: None
  ports:
  - name: galera
    port: 4567
    protocol: TCP
  - name: ist
    port: 4568
    protocol: TCP
  - name: sst
    port: 4444
    protocol: TCP
  selector:
    name: mariadb-galera
  type: ClusterIP
