apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    name: mariadb-galera
  name: mariadb-galera
  namespace: kubeprod
spec:
  replicas: 3
  selector:
    matchLabels:
      name: mariadb-galera
  serviceName: mariadb-galera
  template:
    metadata:
      annotations: {}
      labels:
        name: mariadb-galera
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  name: mariadb-galera
              topologyKey: kubernetes.io/hostname
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  name: mariadb-galera
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  name: mariadb-galera
              topologyKey: failure-domain.beta.kubernetes.io/region
            weight: 70
      containers:
      - args: []
        env:
        - name: MARIADB_GALERA_CLUSTER_ADDRESS
          value: gcomm://mariadb-galera-headless.kubeprod.svc
        - name: MARIADB_GALERA_CLUSTER_NAME
          value: galera
        - name: MARIADB_GALERA_MARIABACKUP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariabackup_password
              name: mariadb-galera-dc69b99
        - name: MARIADB_GALERA_MARIABACKUP_USER
          value: mariabackup
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root_password
              name: mariadb-galera-dc69b99
        image: bitnami/mariadb-galera:10.5.4-debian-10-r2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -ec
            - |
              exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: mariadb-galera
        ports:
        - containerPort: 4567
          name: galera
        - containerPort: 4568
          name: ist
        - containerPort: 3306
          name: mysql
        - containerPort: 4444
          name: sst
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -ec
            - |
              exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        stdin: false
        tty: false
        volumeMounts:
        - mountPath: /opt/bitnami/mariadb/conf/my.cnf
          name: config
          readOnly: true
          subPath: my.cnf
        - mountPath: /bitnami/mariadb
          name: data
      - args: []
        command:
        - sh
        - -c
        - |
          DATA_SOURCE_NAME="root:$MARIADB_ROOT_PASSWORD@(localhost:3306)/" /bin/mysqld_exporter
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root_password
              name: mariadb-galera-dc69b99
        image: bitnami/mysqld-exporter:0.12.1-debian-10-r86
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: metrics
        ports:
        - containerPort: 9104
          name: metrics
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        stdin: false
        tty: false
        volumeMounts: []
      imagePullSecrets: []
      initContainers: []
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccountName: mariadb-galera
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: mariadb-galera-ece316e
        name: config
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      labels:
        name: data
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: "rook-cephfs"
      resources:
        requests:
          storage: 10Gi
