apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations: {}
  labels:
    name: fluentd-es
  name: fluentd-es
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentd-es
subjects:
- kind: ServiceAccount
  name: fluentd-es
  namespace: kubeprod
