apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations: {}
  labels:
    name: cert-manager-issuers
  name: cert-manager-issuers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-issuers
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: kubeprod
