apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  annotations: {}
  labels:
    name: release-reader
  name: release-reader
  namespace: kubeprod
rules:
- apiGroups:
  - ""
  resourceNames:
  - release
  resources:
  - configmap
  verbs:
  - get
  - list
  - watch
