apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  annotations: {}
  labels:
    name: mariadb-galera
  name: mariadb-galera
  namespace: kubeprod
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
