apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  annotations: {}
  labels:
    name: mariadb-galera
  name: mariadb-galera
  namespace: kubeprod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mariadb-galera
subjects:
- kind: ServiceAccount
  name: mariadb-galera
  namespace: kubeprod
