apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations: {}
  labels:
    name: node-exporter
  name: node-exporter
  namespace: kubeprod
spec:
  selector:
    matchLabels:
      name: node-exporter
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      labels:
        name: node-exporter
    spec:
      containers:
      - args:
        - --collector.filesystem.ignored-fs-types=^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs)?$
        - --collector.filesystem.ignored-mount-points=^(/rootfs|/host)?/(sys|proc|dev|host|etc)($|/)
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        env: []
        image: bitnami/node-exporter:1.0.1-debian-10-r4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: scrape
        name: node-exporter
        ports:
        - containerPort: 9100
          name: scrape
        readinessProbe:
          httpGet:
            path: /
            port: scrape
          successThreshold: 2
        stdin: false
        tty: false
        volumeMounts:
        - mountPath: /host/proc
          name: procfs
          readOnly: true
        - mountPath: /rootfs
          name: root
          readOnly: true
        - mountPath: /host/sys
          name: sysfs
          readOnly: true
      hostNetwork: true
      hostPID: true
      imagePullSecrets: []
      initContainers: []
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /proc
          type: ""
        name: procfs
      - hostPath:
          path: /
          type: ""
        name: root
      - hostPath:
          path: /sys
          type: ""
        name: sysfs
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
