apiVersion: v1
data:
  disable-ipv6: "false"
  enable-vts-status: "true"
  hsts: "true"
  http2-max-field-size: 16k
  http2-max-header-size: 64k
  large-client-header-buffers: 8 32k
  no-auth-locations: /.well-known/acme-challenge,/oauth2
  proxy-buffer-size: 32k
  proxy-connect-timeout: "15"
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    name: nginx-ingress
  name: nginx-ingress-0ff949c
  namespace: kubeprod
