apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: nginx-ingress-udp
  name: nginx-ingress-udp
  namespace: kubeprod
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
  selector:
    name: nginx-ingress-controller
  type: LoadBalancer
