- name: Ensure {{ rook_ceph_namespace }} namespace is {{ rook_ceph_state }}
  community.kubernetes.k8s:
    name: "{{ rook_ceph_namespace }}"
    api_version: v1
    kind: Namespace
    state: "{{ rook_ceph_state }}"
    wait: yes

- name: Ensure Rook Ceph operator is {{ rook_ceph_state }}
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'operator.yaml.j2') }}"
    state: "{{ rook_ceph_state }}"
    wait: yes

- name: Ensure Rook Ceph cluster is {{ rook_ceph_state }}
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'cluster.yaml.j2') }}"
    state: "{{ rook_ceph_state }}"
    wait: yes

- name: wait 60 sec for deployment to finish
  wait_for:
    timeout: 60


# TODO move following block storage declaration into a new role 

# - name: Ensure Rook Ceph Block Pool is {{ rook_ceph_state }}
#   community.kubernetes.k8s:
#     definition: "{{ lookup('template', 'ceph-block-pool.yaml.j2') }}"
#     state: "{{ rook_ceph_state }}"
#     wait: yes

# - name: Ensure Rook Ceph storageClass is {{ rook_ceph_state }}
#   community.kubernetes.k8s:
#     definition: "{{ lookup('template', 'storageclass.yaml.j2') }}"
#     state: "{{ rook_ceph_state }}"
#     wait: yes

- name: Ensure Rook Ceph tools pod is {{ rook_ceph_state }}
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'tools.yaml.j2') }}"
    state: "{{ rook_ceph_state }}"
    wait: yes




