apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  annotations: {}
  labels:
    name: letsencrypt-prod
  name: letsencrypt-prod
spec:
  acme:
    email: eliegavoty@free.fr
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
