apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations: {}
  labels:
    name: elasticsearch-curator
  name: elasticsearch-curator
  namespace: kubeprod
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 20
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      template:
        metadata:
          labels:
            name: elasticsearch-curator
        spec:
          containers:
          - args:
            - --config
            - /etc/config/config.yml
            - /etc/config/action_file.yml
            env: []
            image: bitnami/elasticsearch-curator:5.8.1-debian-10-r85
            imagePullPolicy: IfNotPresent
            name: curator
            ports: []
            stdin: false
            tty: false
            volumeMounts:
            - mountPath: /etc/config
              name: config-vol
              readOnly: true
          imagePullSecrets: []
          initContainers: []
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              name: elasticsearch-curator-4f52cd0
            name: config-vol
  schedule: 10 10 * * *
  successfulJobsHistoryLimit: 10
