apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  labels:
    name: kibana-plugins
  name: kibana-plugins
  namespace: kubeprod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-cephfs
