apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations: {}
  labels:
    k8s-app: elasticsearch-logging
    name: elasticsearch-logging
  name: elasticsearch-logging
  namespace: kubeprod
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch-logging
      name: elasticsearch-logging
