- name: Ensure k8s python modules are installed
  hosts: kube_nodes
  become: true

  tasks:
    - name: Ensure python3-pip installed
      apt:
        name: python3-pip
        state: present
        update_cache: yes
      tags: ["python-k8s-modules"]
        
    - name : Ensure k8s python modules are installed
      pip:
        name:
          - kubernetes
          - openshift
        state: present
        executable: pip3
      tags: ["python-k8s-modules"]